"""empty message

Revision ID: db9c86734e1c
Revises: 0d726e81ee5d
Create Date: 2026-01-19 09:31:06.853010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9c86734e1c'
down_revision = '0d726e81ee5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint('empresa_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_unique_constraint('empresa_nombre_key', ['nombre'])

    # ### end Alembic commands ###
